import "./css/style.css";

import { Inter } from "next/font/google";

import { SessionProvider } from "next-auth/react";
import { NextSession } from "@/provider/NextSession";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://assets.usestyle.ai/seonajsplugin" defer id="seona-js-plugin"></script>
      </head>
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <NextSession>
            {children}
          </NextSession>
        </div>
      </body>
    </html>
  );
}
